name: Go Release
on:
  push:
    tags:
      - "v*" # 触发条件：推送以 v 开头的标签，如 v1.0.0

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整的 git 历史以确保版本信息正确

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24" # 指定 Go 版本，根据项目调整

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
